// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go

// Package mock_databasestorage is a generated GoMock package.
package mock_databasestorage

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockdatabaseDB is a mock of databaseDB interface.
type MockdatabaseDB struct {
	ctrl     *gomock.Controller
	recorder *MockdatabaseDBMockRecorder
}

// MockdatabaseDBMockRecorder is the mock recorder for MockdatabaseDB.
type MockdatabaseDBMockRecorder struct {
	mock *MockdatabaseDB
}

// NewMockdatabaseDB creates a new mock instance.
func NewMockdatabaseDB(ctrl *gomock.Controller) *MockdatabaseDB {
	mock := &MockdatabaseDB{ctrl: ctrl}
	mock.recorder = &MockdatabaseDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdatabaseDB) EXPECT() *MockdatabaseDBMockRecorder {
	return m.recorder
}

// ExecContext mocks base method.
func (m *MockdatabaseDB) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecContext", varargs...)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecContext indicates an expected call of ExecContext.
func (mr *MockdatabaseDBMockRecorder) ExecContext(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecContext", reflect.TypeOf((*MockdatabaseDB)(nil).ExecContext), varargs...)
}

// QueryRowContext mocks base method.
func (m *MockdatabaseDB) QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRowContext", varargs...)
	ret0, _ := ret[0].(*sql.Row)
	return ret0
}

// QueryRowContext indicates an expected call of QueryRowContext.
func (mr *MockdatabaseDBMockRecorder) QueryRowContext(ctx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRowContext", reflect.TypeOf((*MockdatabaseDB)(nil).QueryRowContext), varargs...)
}
