// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: objects.proto

package protobufproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         int64                  `protobuf:"varint,1,opt,name=Delta,proto3" json:"Delta,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=Value,proto3" json:"Value,omitempty"`
	ID            string                 `protobuf:"bytes,3,opt,name=ID,proto3" json:"ID,omitempty"`
	MType         string                 `protobuf:"bytes,4,opt,name=MType,proto3" json:"MType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMetric) Reset() {
	*x = RequestMetric{}
	mi := &file_objects_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMetric) ProtoMessage() {}

func (x *RequestMetric) ProtoReflect() protoreflect.Message {
	mi := &file_objects_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMetric.ProtoReflect.Descriptor instead.
func (*RequestMetric) Descriptor() ([]byte, []int) {
	return file_objects_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMetric) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *RequestMetric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *RequestMetric) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *RequestMetric) GetMType() string {
	if x != nil {
		return x.MType
	}
	return ""
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_objects_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_objects_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_objects_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type RequestAnsMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Delta         int64                  `protobuf:"varint,2,opt,name=Delta,proto3" json:"Delta,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=Value,proto3" json:"Value,omitempty"`
	ID            string                 `protobuf:"bytes,4,opt,name=ID,proto3" json:"ID,omitempty"`
	MType         string                 `protobuf:"bytes,5,opt,name=MType,proto3" json:"MType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAnsMetric) Reset() {
	*x = RequestAnsMetric{}
	mi := &file_objects_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAnsMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAnsMetric) ProtoMessage() {}

func (x *RequestAnsMetric) ProtoReflect() protoreflect.Message {
	mi := &file_objects_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAnsMetric.ProtoReflect.Descriptor instead.
func (*RequestAnsMetric) Descriptor() ([]byte, []int) {
	return file_objects_proto_rawDescGZIP(), []int{2}
}

func (x *RequestAnsMetric) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RequestAnsMetric) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *RequestAnsMetric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *RequestAnsMetric) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *RequestAnsMetric) GetMType() string {
	if x != nil {
		return x.MType
	}
	return ""
}

var File_objects_proto protoreflect.FileDescriptor

const file_objects_proto_rawDesc = "" +
	"\n" +
	"\robjects.proto\x12\rprotobufproto\"a\n" +
	"\rRequestMetric\x12\x14\n" +
	"\x05Delta\x18\x01 \x01(\x03R\x05Delta\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\x01R\x05Value\x12\x0e\n" +
	"\x02ID\x18\x03 \x01(\tR\x02ID\x12\x14\n" +
	"\x05MType\x18\x04 \x01(\tR\x05MType\" \n" +
	"\x06Status\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\x05R\x06Status\"|\n" +
	"\x10RequestAnsMetric\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\x05R\x06Status\x12\x14\n" +
	"\x05Delta\x18\x02 \x01(\x03R\x05Delta\x12\x14\n" +
	"\x05Value\x18\x03 \x01(\x01R\x05Value\x12\x0e\n" +
	"\x02ID\x18\x04 \x01(\tR\x02ID\x12\x14\n" +
	"\x05MType\x18\x05 \x01(\tR\x05MType2\x9b\x01\n" +
	"\x12GRPCMetricsService\x12=\n" +
	"\x06Update\x12\x1c.protobufproto.RequestMetric\x1a\x15.protobufproto.Status\x12F\n" +
	"\x05Value\x12\x1c.protobufproto.RequestMetric\x1a\x1f.protobufproto.RequestAnsMetricB\x15Z\x13proto/protobufprotob\x06proto3"

var (
	file_objects_proto_rawDescOnce sync.Once
	file_objects_proto_rawDescData []byte
)

func file_objects_proto_rawDescGZIP() []byte {
	file_objects_proto_rawDescOnce.Do(func() {
		file_objects_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_objects_proto_rawDesc), len(file_objects_proto_rawDesc)))
	})
	return file_objects_proto_rawDescData
}

var file_objects_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_objects_proto_goTypes = []any{
	(*RequestMetric)(nil),    // 0: protobufproto.RequestMetric
	(*Status)(nil),           // 1: protobufproto.Status
	(*RequestAnsMetric)(nil), // 2: protobufproto.RequestAnsMetric
}
var file_objects_proto_depIdxs = []int32{
	0, // 0: protobufproto.GRPCMetricsService.Update:input_type -> protobufproto.RequestMetric
	0, // 1: protobufproto.GRPCMetricsService.Value:input_type -> protobufproto.RequestMetric
	1, // 2: protobufproto.GRPCMetricsService.Update:output_type -> protobufproto.Status
	2, // 3: protobufproto.GRPCMetricsService.Value:output_type -> protobufproto.RequestAnsMetric
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_objects_proto_init() }
func file_objects_proto_init() {
	if File_objects_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_objects_proto_rawDesc), len(file_objects_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_objects_proto_goTypes,
		DependencyIndexes: file_objects_proto_depIdxs,
		MessageInfos:      file_objects_proto_msgTypes,
	}.Build()
	File_objects_proto = out.File
	file_objects_proto_goTypes = nil
	file_objects_proto_depIdxs = nil
}
